# Mochi world server configuration
# After editing, run 'systemctl restart mochi-world'
# See mochi-world(8) for full details.

[world]
name = My world server
public = true

#[transport]
#address = https://yourdomain:4433

#[tls]
#certificate = /etc/ssl/certs/yourdomain.pem
#key = /etc/ssl/private/yourdomain.pem

#[acme]
#hosts = yourdomain
